spring:
  application:
    name: date-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:transneftpua_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      data-source-properties:
        application-name: "Microservice: ${spring.application.name} (${USERNAME})"
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_updates: true
        generate_statistics: true
        cache:
          use_second_level_cache: false
    show-sql: true
  sql:
    init:
      mode: never
logging:
  level:
    root: warn
    ru.sitronics.tn: debug